FROM openjdk:11
EXPOSE 8080
ADD target/subbu-casestudy-microservices-docker-dockerhub.jar subbu-casestudy-microservices-docker-dockerhub.jar
ENTRYPOINT ["java", "-jar", "/subbu-casestudy-microservices-docker-dockerhub.jar"]